// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateAPIRequestBody struct {
	// The name for your API. This is not customer facing.
	Name string `json:"name"`
}

func (o *CreateAPIRequestBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

// CreateAPIResponseBody - The configuration for an api
type CreateAPIResponseBody struct {
	// The id of the api
	APIID string `json:"apiId"`
}

func (o *CreateAPIResponseBody) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

type CreateAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The configuration for an api
	Object *CreateAPIResponseBody
}

func (o *CreateAPIResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateAPIResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateAPIResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateAPIResponse) GetObject() *CreateAPIResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
