// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteKeyRequestBody struct {
	// The id of the key to revoke
	KeyID string `json:"keyId"`
}

func (o *DeleteKeyRequestBody) GetKeyID() string {
	if o == nil {
		return ""
	}
	return o.KeyID
}

// DeleteKeyResponseBody - The key was successfully revoked, it may take up to 30s for this to take effect in all regions
type DeleteKeyResponseBody struct {
}

type DeleteKeyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The key was successfully revoked, it may take up to 30s for this to take effect in all regions
	Object *DeleteKeyResponseBody
}

func (o *DeleteKeyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteKeyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteKeyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteKeyResponse) GetObject() *DeleteKeyResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
