// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAPIRequestBody struct {
	// The id of the api to delete
	APIID string `json:"apiId"`
}

func (o *DeleteAPIRequestBody) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

// DeleteAPIResponseBody - The api was successfully deleted, it may take up to 30s for this to take effect in all regions
type DeleteAPIResponseBody struct {
}

type DeleteAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The api was successfully deleted, it may take up to 30s for this to take effect in all regions
	Object *DeleteAPIResponseBody
}

func (o *DeleteAPIResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteAPIResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteAPIResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteAPIResponse) GetObject() *DeleteAPIResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
