// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAPIRequest struct {
	APIID string `queryParam:"style=form,explode=true,name=apiId"`
}

func (o *GetAPIRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

// GetAPIResponseBody - The configuration for an api
type GetAPIResponseBody struct {
	// The id of the key
	ID string `json:"id"`
	// The name of the api. This is internal and your users will not see this.
	Name *string `json:"name,omitempty"`
	// The id of the workspace that owns the api
	WorkspaceID string `json:"workspaceId"`
}

func (o *GetAPIResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetAPIResponseBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *GetAPIResponseBody) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

type GetAPIResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The configuration for an api
	Object *GetAPIResponseBody
}

func (o *GetAPIResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPIResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPIResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAPIResponse) GetObject() *GetAPIResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
