// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type GetKeyRequest struct {
	KeyID string `queryParam:"style=form,explode=true,name=keyId"`
}

func (o *GetKeyRequest) GetKeyID() string {
	if o == nil {
		return ""
	}
	return o.KeyID
}

type GetKeyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The configuration for a single key
	Key *shared.Key
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetKeyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetKeyResponse) GetKey() *shared.Key {
	if o == nil {
		return nil
	}
	return o.Key
}

func (o *GetKeyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetKeyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
