// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type Services struct {
	// The name of the connected analytics service
	Analytics string `json:"analytics"`
	// The name of the connected logger service
	Logger string `json:"logger"`
	// The name of the connected metrics service
	Metrics string `json:"metrics"`
	// The name of the connected ratelimit service
	Ratelimit string `json:"ratelimit"`
	// The name of the connected usagelimit service
	Usagelimit string `json:"usagelimit"`
}

func (o *Services) GetAnalytics() string {
	if o == nil {
		return ""
	}
	return o.Analytics
}

func (o *Services) GetLogger() string {
	if o == nil {
		return ""
	}
	return o.Logger
}

func (o *Services) GetMetrics() string {
	if o == nil {
		return ""
	}
	return o.Metrics
}

func (o *Services) GetRatelimit() string {
	if o == nil {
		return ""
	}
	return o.Ratelimit
}

func (o *Services) GetUsagelimit() string {
	if o == nil {
		return ""
	}
	return o.Usagelimit
}

// GetV1LivenessResponseBody - The configured services and their status
type GetV1LivenessResponseBody struct {
	Services Services `json:"services"`
	// The status of the server
	Status string `json:"status"`
}

func (o *GetV1LivenessResponseBody) GetServices() Services {
	if o == nil {
		return Services{}
	}
	return o.Services
}

func (o *GetV1LivenessResponseBody) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

type GetV1LivenessResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The configured services and their status
	Object *GetV1LivenessResponseBody
}

func (o *GetV1LivenessResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetV1LivenessResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetV1LivenessResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetV1LivenessResponse) GetObject() *GetV1LivenessResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
