// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
	"openapi/pkg/utils"
)

type ListKeysRequest struct {
	APIID   string  `queryParam:"style=form,explode=true,name=apiId"`
	Cursor  *string `queryParam:"style=form,explode=true,name=cursor"`
	Limit   *int64  `default:"100" queryParam:"style=form,explode=true,name=limit"`
	OwnerID *string `queryParam:"style=form,explode=true,name=ownerId"`
}

func (l ListKeysRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListKeysRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListKeysRequest) GetAPIID() string {
	if o == nil {
		return ""
	}
	return o.APIID
}

func (o *ListKeysRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ListKeysRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListKeysRequest) GetOwnerID() *string {
	if o == nil {
		return nil
	}
	return o.OwnerID
}

// ListKeysResponseBody - The configuration for an api
type ListKeysResponseBody struct {
	// The cursor to use for the next page of results, if no cursor is returned, there are no more results
	Cursor *string      `json:"cursor,omitempty"`
	Keys   []shared.Key `json:"keys"`
	// The total number of keys for this api
	Total int64 `json:"total"`
}

func (o *ListKeysResponseBody) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *ListKeysResponseBody) GetKeys() []shared.Key {
	if o == nil {
		return []shared.Key{}
	}
	return o.Keys
}

func (o *ListKeysResponseBody) GetTotal() int64 {
	if o == nil {
		return 0
	}
	return o.Total
}

type ListKeysResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The configuration for an api
	Object *ListKeysResponseBody
}

func (o *ListKeysResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListKeysResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListKeysResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListKeysResponse) GetObject() *ListKeysResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
