// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openapi/pkg/models/shared"
)

type VerifyKeyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The verification result
	V1KeysVerifyKeyResponse *shared.V1KeysVerifyKeyResponse
}

func (o *VerifyKeyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *VerifyKeyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *VerifyKeyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *VerifyKeyResponse) GetV1KeysVerifyKeyResponse() *shared.V1KeysVerifyKeyResponse {
	if o == nil {
		return nil
	}
	return o.V1KeysVerifyKeyResponse
}
