// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// SchemasCode - A machine readable error code.
type SchemasCode string

const (
	SchemasCodeConflict SchemasCode = "CONFLICT"
)

func (e SchemasCode) ToPointer() *SchemasCode {
	return &e
}

func (e *SchemasCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CONFLICT":
		*e = SchemasCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasCode: %v", v)
	}
}

type SchemasError struct {
	// A machine readable error code.
	Code SchemasCode `json:"code"`
	// A link to our documentation with more details about this error code
	Docs string `json:"docs"`
	// A human readable explanation of what went wrong
	Message string `json:"message"`
	// Please always include the requestId in your error report
	RequestID string `json:"requestId"`
}

func (o *SchemasError) GetCode() SchemasCode {
	if o == nil {
		return SchemasCode("")
	}
	return o.Code
}

func (o *SchemasError) GetDocs() string {
	if o == nil {
		return ""
	}
	return o.Docs
}

func (o *SchemasError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *SchemasError) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

// ErrConflict - This response is sent when a request conflicts with the current state of the server.
type ErrConflict struct {
	Error_ SchemasError `json:"error"`
}

var _ error = &ErrConflict{}

func (e *ErrConflict) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
