// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// SchemasErrForbiddenCode - A machine readable error code.
type SchemasErrForbiddenCode string

const (
	SchemasErrForbiddenCodeForbidden SchemasErrForbiddenCode = "FORBIDDEN"
)

func (e SchemasErrForbiddenCode) ToPointer() *SchemasErrForbiddenCode {
	return &e
}

func (e *SchemasErrForbiddenCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FORBIDDEN":
		*e = SchemasErrForbiddenCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasErrForbiddenCode: %v", v)
	}
}

type SchemasErrForbiddenError struct {
	// A machine readable error code.
	Code SchemasErrForbiddenCode `json:"code"`
	// A link to our documentation with more details about this error code
	Docs string `json:"docs"`
	// A human readable explanation of what went wrong
	Message string `json:"message"`
	// Please always include the requestId in your error report
	RequestID string `json:"requestId"`
}

func (o *SchemasErrForbiddenError) GetCode() SchemasErrForbiddenCode {
	if o == nil {
		return SchemasErrForbiddenCode("")
	}
	return o.Code
}

func (o *SchemasErrForbiddenError) GetDocs() string {
	if o == nil {
		return ""
	}
	return o.Docs
}

func (o *SchemasErrForbiddenError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *SchemasErrForbiddenError) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

// ErrForbidden - The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.
type ErrForbidden struct {
	Error_ SchemasErrForbiddenError `json:"error"`
}

var _ error = &ErrForbidden{}

func (e *ErrForbidden) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
