// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// SchemasErrNotFoundCode - A machine readable error code.
type SchemasErrNotFoundCode string

const (
	SchemasErrNotFoundCodeNotFound SchemasErrNotFoundCode = "NOT_FOUND"
)

func (e SchemasErrNotFoundCode) ToPointer() *SchemasErrNotFoundCode {
	return &e
}

func (e *SchemasErrNotFoundCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NOT_FOUND":
		*e = SchemasErrNotFoundCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasErrNotFoundCode: %v", v)
	}
}

type SchemasErrNotFoundError struct {
	// A machine readable error code.
	Code SchemasErrNotFoundCode `json:"code"`
	// A link to our documentation with more details about this error code
	Docs string `json:"docs"`
	// A human readable explanation of what went wrong
	Message string `json:"message"`
	// Please always include the requestId in your error report
	RequestID string `json:"requestId"`
}

func (o *SchemasErrNotFoundError) GetCode() SchemasErrNotFoundCode {
	if o == nil {
		return SchemasErrNotFoundCode("")
	}
	return o.Code
}

func (o *SchemasErrNotFoundError) GetDocs() string {
	if o == nil {
		return ""
	}
	return o.Docs
}

func (o *SchemasErrNotFoundError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *SchemasErrNotFoundError) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

// ErrNotFound - The server cannot find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web.
type ErrNotFound struct {
	Error_ SchemasErrNotFoundError `json:"error"`
}

var _ error = &ErrNotFound{}

func (e *ErrNotFound) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
