// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// SchemasErrTooManyRequestsCode - A machine readable error code.
type SchemasErrTooManyRequestsCode string

const (
	SchemasErrTooManyRequestsCodeTooManyRequests SchemasErrTooManyRequestsCode = "TOO_MANY_REQUESTS"
)

func (e SchemasErrTooManyRequestsCode) ToPointer() *SchemasErrTooManyRequestsCode {
	return &e
}

func (e *SchemasErrTooManyRequestsCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TOO_MANY_REQUESTS":
		*e = SchemasErrTooManyRequestsCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasErrTooManyRequestsCode: %v", v)
	}
}

type SchemasErrTooManyRequestsError struct {
	// A machine readable error code.
	Code SchemasErrTooManyRequestsCode `json:"code"`
	// A link to our documentation with more details about this error code
	Docs string `json:"docs"`
	// A human readable explanation of what went wrong
	Message string `json:"message"`
	// Please always include the requestId in your error report
	RequestID string `json:"requestId"`
}

func (o *SchemasErrTooManyRequestsError) GetCode() SchemasErrTooManyRequestsCode {
	if o == nil {
		return SchemasErrTooManyRequestsCode("")
	}
	return o.Code
}

func (o *SchemasErrTooManyRequestsError) GetDocs() string {
	if o == nil {
		return ""
	}
	return o.Docs
}

func (o *SchemasErrTooManyRequestsError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *SchemasErrTooManyRequestsError) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

// ErrTooManyRequests - The user has sent too many requests in a given amount of time ("rate limiting")
type ErrTooManyRequests struct {
	Error_ SchemasErrTooManyRequestsError `json:"error"`
}

var _ error = &ErrTooManyRequests{}

func (e *ErrTooManyRequests) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
