/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * A machine readable error code.
 */
export enum ErrTooManyRequestsCode {
    TooManyRequests = "TOO_MANY_REQUESTS",
}

export class ErrTooManyRequestsError extends SpeakeasyBase {
    /**
     * A machine readable error code.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code: ErrTooManyRequestsCode;

    /**
     * A link to our documentation with more details about this error code
     */
    @SpeakeasyMetadata()
    @Expose({ name: "docs" })
    docs: string;

    /**
     * A human readable explanation of what went wrong
     */
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    message: string;

    /**
     * Please always include the requestId in your error report
     */
    @SpeakeasyMetadata()
    @Expose({ name: "requestId" })
    requestId: string;
}

export class ErrTooManyRequests extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    @Type(() => ErrTooManyRequestsError)
    error: ErrTooManyRequestsError;
}
