/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * If the key is invalid this field will be set to the reason why it is invalid.
 *
 * @remarks
 * Possible values are:
 * - NOT_FOUND: the key does not exist or has expired
 * - FORBIDDEN: the key is not allowed to access the api
 * - USAGE_EXCEEDED: the key has exceeded its request limit
 * - RATE_LIMITED: the key has been ratelimited
 * - UNAUTHORIZED: the key is not authorized
 * - DISABLED: the key is disabled
 * - INSUFFICIENT_PERMISSIONS: you do not have the required permissions to perform this action
 *
 */
export enum Code {
    NotFound = "NOT_FOUND",
    Forbidden = "FORBIDDEN",
    UsageExceeded = "USAGE_EXCEEDED",
    RateLimited = "RATE_LIMITED",
    Unauthorized = "UNAUTHORIZED",
    Disabled = "DISABLED",
    InsufficientPermissions = "INSUFFICIENT_PERMISSIONS",
}

/**
 * The ratelimit configuration for this key. If this field is null or undefined, the key has no ratelimit.
 */
export class V1KeysVerifyKeyResponseRatelimit extends SpeakeasyBase {
    /**
     * Maximum number of requests that can be made inside a window
     */
    @SpeakeasyMetadata()
    @Expose({ name: "limit" })
    limit: number;

    /**
     * Remaining requests after this verification
     */
    @SpeakeasyMetadata()
    @Expose({ name: "remaining" })
    remaining: number;

    /**
     * Unix timestamp in milliseconds when the ratelimit will reset
     */
    @SpeakeasyMetadata()
    @Expose({ name: "reset" })
    reset: number;
}

export class V1KeysVerifyKeyResponse extends SpeakeasyBase {
    /**
     * If the key is invalid this field will be set to the reason why it is invalid.
     *
     * @remarks
     * Possible values are:
     * - NOT_FOUND: the key does not exist or has expired
     * - FORBIDDEN: the key is not allowed to access the api
     * - USAGE_EXCEEDED: the key has exceeded its request limit
     * - RATE_LIMITED: the key has been ratelimited
     * - UNAUTHORIZED: the key is not authorized
     * - DISABLED: the key is disabled
     * - INSUFFICIENT_PERMISSIONS: you do not have the required permissions to perform this action
     *
     */
    @SpeakeasyMetadata()
    @Expose({ name: "code" })
    code?: Code;

    /**
     * Sets the key to be enabled or disabled. Disabled keys will not verify.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "enabled" })
    enabled?: boolean;

    /**
     * The unix timestamp in milliseconds when the key will expire. If this field is null or undefined, the key is not expiring.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "expires" })
    expires?: number;

    /**
     * The id of the key
     */
    @SpeakeasyMetadata()
    @Expose({ name: "keyId" })
    keyId?: string;

    /**
     * Any additional metadata you want to store with the key
     */
    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    meta?: Record<string, any>;

    /**
     * The name of the key, give keys a name to easily identifiy their purpose
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * The id of the tenant associated with this key. Use whatever reference you have in your system to identify the tenant. When verifying the key, we will send this field back to you, so you know who is accessing your API.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ownerId" })
    ownerId?: string;

    /**
     * The ratelimit configuration for this key. If this field is null or undefined, the key has no ratelimit.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ratelimit" })
    @Type(() => V1KeysVerifyKeyResponseRatelimit)
    ratelimit?: V1KeysVerifyKeyResponseRatelimit;

    /**
     * The number of requests that can be made with this key before it becomes invalid. If this field is null or undefined, the key has no request limit.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "remaining" })
    remaining?: number;

    /**
     * Whether the key is valid or not.
     *
     * @remarks
     * A key could be invalid for a number of reasons, for example if it has expired, has no more verifications left or if it has been deleted.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "valid" })
    valid: boolean;
}
