// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type V1KeysVerifyKeyRequest struct {
	// The id of the api where the key belongs to. This is optional for now but will be required soon.
	// The key will be verified against the api's configuration. If the key does not belong to the api, the verification will fail.
	APIID *string `json:"apiId,omitempty"`
	// The key to verify
	Key string `json:"key"`
}

func (o *V1KeysVerifyKeyRequest) GetAPIID() *string {
	if o == nil {
		return nil
	}
	return o.APIID
}

func (o *V1KeysVerifyKeyRequest) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}
