/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import { z } from "zod";

export type GetV1ApisApiIdKeysRequest = {
    apiId: string;
    limit?: number | undefined;
    offset?: number | null | undefined;
    ownerId?: string | undefined;
};

/**
 * Keys belonging to the api
 */
export type GetV1ApisApiIdKeysResponseBody = {
    keys: Array<components.Key>;
    /**
     * The total number of keys for this api
     */
    total: number;
};

export type GetV1ApisApiIdKeysResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Keys belonging to the api
     */
    object?: GetV1ApisApiIdKeysResponseBody | undefined;
};

/** @internal */
export namespace GetV1ApisApiIdKeysRequest$ {
    export type Inbound = {
        apiId: string;
        limit?: number | undefined;
        offset?: number | null | undefined;
        ownerId?: string | undefined;
    };

    export const inboundSchema: z.ZodType<GetV1ApisApiIdKeysRequest, z.ZodTypeDef, Inbound> = z
        .object({
            apiId: z.string(),
            limit: z.number().int().default(100),
            offset: z.nullable(z.number()).optional(),
            ownerId: z.string().optional(),
        })
        .transform((v) => {
            return {
                apiId: v.apiId,
                limit: v.limit,
                ...(v.offset === undefined ? null : { offset: v.offset }),
                ...(v.ownerId === undefined ? null : { ownerId: v.ownerId }),
            };
        });

    export type Outbound = {
        apiId: string;
        limit: number;
        offset?: number | null | undefined;
        ownerId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetV1ApisApiIdKeysRequest> = z
        .object({
            apiId: z.string(),
            limit: z.number().int().default(100),
            offset: z.nullable(z.number()).optional(),
            ownerId: z.string().optional(),
        })
        .transform((v) => {
            return {
                apiId: v.apiId,
                limit: v.limit,
                ...(v.offset === undefined ? null : { offset: v.offset }),
                ...(v.ownerId === undefined ? null : { ownerId: v.ownerId }),
            };
        });
}

/** @internal */
export namespace GetV1ApisApiIdKeysResponseBody$ {
    export type Inbound = {
        keys: Array<components.Key$.Inbound>;
        total: number;
    };

    export const inboundSchema: z.ZodType<GetV1ApisApiIdKeysResponseBody, z.ZodTypeDef, Inbound> = z
        .object({
            keys: z.array(components.Key$.inboundSchema),
            total: z.number().int(),
        })
        .transform((v) => {
            return {
                keys: v.keys,
                total: v.total,
            };
        });

    export type Outbound = {
        keys: Array<components.Key$.Outbound>;
        total: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetV1ApisApiIdKeysResponseBody> =
        z
            .object({
                keys: z.array(components.Key$.outboundSchema),
                total: z.number().int(),
            })
            .transform((v) => {
                return {
                    keys: v.keys,
                    total: v.total,
                };
            });
}

/** @internal */
export namespace GetV1ApisApiIdKeysResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
        object?: GetV1ApisApiIdKeysResponseBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetV1ApisApiIdKeysResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            object: z.lazy(() => GetV1ApisApiIdKeysResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        object?: GetV1ApisApiIdKeysResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetV1ApisApiIdKeysResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            object: z.lazy(() => GetV1ApisApiIdKeysResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
