/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = {
    bearerAuth?: string | undefined;
};

/** @internal */
export namespace Security$ {
    export type Inbound = {
        bearerAuth?: string | undefined;
    };

    export const inboundSchema: z.ZodType<Security, z.ZodTypeDef, Inbound> = z
        .object({
            bearerAuth: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.bearerAuth === undefined ? null : { bearerAuth: v.bearerAuth }),
            };
        });

    export type Outbound = {
        bearerAuth?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Security> = z
        .object({
            bearerAuth: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.bearerAuth === undefined ? null : { bearerAuth: v.bearerAuth }),
            };
        });
}
